source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SwiftCarousel_Example', :exclusive => true do
  pod "SwiftCarousel", :path => "../"
end

target 'SwiftCarousel_Tests', :exclusive => true do
  pod "SwiftCarousel", :path => "../"

  
end
